# MySQL
mysql:
    host: "127.0.0.1"
    user: "user"
    passwd: "password"
    database: "dbname"

# XenAPI
xs:
    # url to master xcp-ng
    url: "https://my.domain.com"
    # root login
    login: "root"
    # root password
    pwd: "mysecretpassword"

# web password - default 'admin'
# new password generate via /doc/BCrypt.py
web_password: $2b$12$TG/TPZEXG3dkjR7687hSAOjeGNazKhIl5WtyesDDcyA/6jS7CkMeC

# keep number of versions in db - default '10'
number_of_versions: 10
